Announcing WCGI
wasmerio/wasmer.io pull request #97
Opened 2023-04-03 14:03 UTC by Michael-F-Bryan

2023-04-03 17:41 UTC, dynamite-bud requested changes
That was a really good read @Michael-F-Bryan . Some minor fixes

2023-04-03 17:41 UTC, dynamite-bud commented on _posts/announcing-wcgi.md
> +```bash
All the `bash` entries need to be modified to `shell-session` as bash modifier doesn't work well with our current markdown implementation.

2023-04-03 17:41 UTC, dynamite-bud commented on _posts/announcing-wcgi.md
> +```toml
Is it supposed to be `toml` ?

2023-04-03 17:41 UTC, dynamite-bud commented on _posts/announcing-wcgi.md
> +```bash
I believe this is `toml`

2023-04-03 17:41 UTC, dynamite-bud commented on _posts/announcing-wcgi.md
> +![2023-03-31_14-00.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/8d382cbe-fe56-435b-95af-c645cb02f026/2023-03-31_14-00.png)
you need to change links here @Michael-F-Bryan

2023-04-03 17:41 UTC, dynamite-bud commented on _posts/announcing-wcgi.md
> +![2023-03-31_13-59.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/e27f4b91-ca8e-40b1-a372-dfaef9654d24/2023-03-31_13-59.png)
Link, Here as well

2023-04-03 17:41 UTC, dynamite-bud commented on _posts/announcing-wcgi.md
> +Furthermore, it also closely mirrors the workers proposal from the **[Winter
Can we have a link to the workers proposal ?

2023-04-03 17:48 UTC, syrusakbary commented on _posts/announcing-wcgi.md
> +latency.
> Interestingly, CGI can outperform many other serverless
solutions (such as WSGI in Python/Ruby or NodeJS) in terms of scalability and
latency.

I believe this, but what we are baking up it with? Is there real data to justify this?

2023-04-03 17:48 UTC, syrusakbary commented on _posts/announcing-wcgi.md
> +```toml
Nope, bash it is

```suggestion
```bash
```

2023-04-05 10:00 UTC, syrusakbary commented on _posts/announcing-wcgi.md
> +Now we need to create a `wapm.toml` file.
```suggestion
Now we need to create a `wsmer.toml` file.
```

2023-04-06 04:21 UTC, merged